### ISSUE TITLE
Vaadin 8- ExporterOption

### ISSUE THREAD

**Issue by dsoumis** [haiwan/Exporter#35]
I am running Vaadin 8 and using version 2.0.2 I export a grid in Excel. I also use ExporterOption as indicated in the release notes. However, it does not work as inclined. More specifically, I am not able to change the name of the column in the exported excel file, whatever I try.

**Comment by simpletasks** [comment]
Created fix on #36 PR. Tested with exporter-demo. The main fix is in the FIleBuilder class.
Fix is on v2.1.0 on v8 branch.

**Comment by dsoumis** [comment]
> Created fix on #36 PR. Tested with exporter-demo. The main fix is in the FIleBuilder class.
> Fix is on v2.1.0 on v8 branch.

My gratitude to you for your fix.
